#!/bin/bash

function die {
  printf "\e[4;1;31m$1\e[0m\n"
  exit 1
}

function section {
  printf "\e[4;1;34m$1\e[0m\n"
}

function brew_update {
  brew update
  brew bundle
}

section "Checking prerequisites..."

[[ `uname` == 'Darwin' ]] || die "Currently, only Mac OS X is supported. Please contribute if you'd like to support other development environments!"
type brew 2>/dev/null || die "Homebrew installation not found. Install it here: https://brew.sh/"

section "Updating dependencies..."

brew bundle check --no-upgrade || brew_update
brew bootstrap-nodenv-node
brew bundle exec npm install
